### ISSUE TITLE
attributes.csv location

### ISSUE THREAD

**Issue by CuriousTimo** [dirkjanfaber/node-red-contrib-victron-modbus#1] opened 2023-07-08 09:25 UTC
Is this meant to be run on VenusOS locally or can you copy the attributes.csv over to a location on an external Node-Red installation?

If it is only meant for running locally then a nice feature request would be to be able to upload the attributes.csv file on an external Node-Red installation.

**Comment by dirkjanfaber** [comment] 2023-07-08 09:28
It currently is expecting the file on a Venus OS locally at `/opt/victronenergy/dbus-modbustcp/attributes.csv`. But the suggestion to configure it is good. I'll leave this issue open for adding it.

**Comment by Kositch** [comment] 2023-07-22 20:34
So if I am right - this palette won't work on external RPi running Node-RED? I would like to connect it to my Cerbo on same LAN.

Update: I have manually uploaded attributes.csv (downloaded from VictronEnergy Github) to location /opt/victronenergy/dbus-modbustcp/attributes.csv on my RPi running NR, installed this plugin and works flawlessly even though it is not running on Venus OS on Cerbo - my RPi is pulling data from Cerbo GX.

**Comment by 11awe** [comment] 2023-09-27 23:33
@Kositch 
Can you please share the link you downloaded the attributes.csv from VictronEnergy Github? I was not able to find it

**Comment by dirkjanfaber** [comment] 2023-09-28 06:11
@11awe : you can get the `attributes.csv` file from https://github.com/victronenergy/dbus_modbustcp 

Still need to add the download option to the client. But things have been a bit busy with higher priority stuff lately.

**Comment by 11awe** [comment] 2023-09-28 20:37
Thank you, I'll try to go this way on my Pi. 

Node works well using NodeRed on MP itself.

Reading state of relay 1 and 2 shows correct state. Is is true that I cannot write/control the relays (running MP2 GX, not Cerbo)? Sending 0/1 throws an error (visible in remote console)

**Comment by dirkjanfaber** [comment] 2023-09-29 07:04
Relays need to be set to function "manual" in order to control them remotely. You can set that via the Remote Console.

**Comment by pieslinger** [comment] 2023-11-26 03:10
If the node looks here for the attributes.csv:

RED.settings.userDir + '/attributes.csv'

I do not think it works with nodered running in a docker container.

I can read the attributes.csv with a file node as long as the file node is setup to look at: "/data/attributes.csv".

Would you consider adding an additional  file location to support docker installs?

**Comment by pieslinger** [comment] 2023-11-26 05:58
Disregard - I think the problem is that the .csv file must be in place before the node is dragged to the canvas. Not the file location. Sorry.

**Comment by dirkjanfaber** [comment] 2023-11-26 06:23
Yes, that is true. And I see that I had forgotten to close this issue with that last update. Closing it now.

**Closed as completed by dirkjanfaber** 2023-11-26 06:23 UTC
